---
- hosts: Webserver-With-Monitoring
  become: true
  vars:
    project_name: urlshortener
    project_repo: https://github.com/ianshulx/url-shortener.git
    system_packages:
      - python3
      - python3-venv
      - python3-pip
      - git
      - nginx
      - gunicorn

  tasks:
    - name: Update system packages
      apt:
        update_cache: true
        upgrade: dist

    - name: Install system dependencies
      apt:
        name: "{{ system_packages }}"
        state: present

    - name: Install virtualenv
      apt:
        name: python3-venv
        state: present

    - name: Create Python virtual environment
      command: python3 -m venv /opt/{{ project_name }}/venv
      args:
        creates: /opt/{{ project_name }}/venv
    
    - name: Activate virtual environment and install pip
      command: /opt/{{ project_name }}/venv/bin/python -m ensurepip
    
    - name: Upgrade pip
      command: /opt/{{ project_name }}/venv/bin/pip install --upgrade pip
    
    - name: Install Python dependencies for project
      command: /opt/{{ project_name }}/venv/bin/pip install -r /opt/{{ project_name }}/URL\ Shortener/requirements.txt
    - name: Install required python packages inside virtual environment
      command: "/opt/{{ project_name }}/venv/bin/pip install ansible six"

    - name: Create project directory
      file:
        path: "/opt/{{ project_name }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '600'

    - name: Remove existing project directory if it exists
      file:
        path: "/opt/{{ project_name }}"
        state: absent

    - name: Clone Django URL Shortener project
      git:
        repo: "{{ project_repo }}"
        dest: "/opt/{{ project_name }}"
        version: main
        depth: 1
        force: true

    - name: Configure Gunicorn service
      template:
        src: gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
        mode: '0644'
      notify: Restart Gunicorn

    - name: Ensure Gunicorn is running
      systemd:
        name: gunicorn
        enabled: true
        state: started

  handlers:
    - name: Restart Gunicorn
      systemd:
        name: gunicorn
        state: restarted

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
